### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by shivamjawahar** [ratulSharker/Havec#1]
sufficient number of argument is not passed                                                                                    
 'fileName' 'khmersize' 'howManyHash' 'cut-off or no cut-off' 'print or not print' 'hashSize' 'multiplying factor'

**Comment by ratulSharker** [comment]
Please let me know, how you tried to run **Havec** ?

The error message you're getting means you have successfully compiled **Havec**, but did not passed enough number of arguments to run it properly. 

Try running the test cases by 

```shell
  sh test_run.sh
```

Here you will complete [**Readme.md**](https://github.com/ratulSharker/Havec/blob/master/README.md) guiding you through the build and run with test data sets.

The running procedure is following 

```shell

./Havec.out dataset_1_7GB.fa 32 8 NC NP 138568143 1.4

```
Here 

1. `dataset_1_7GB.fa` is the input file path.
2. `32` KhmerSize (how long the khmer will be taken)
3. `8` how many hash function will be used to encode the khmer
4. `NC` no cutoff will be used.
5. `NP` do not print the debug information
6. `138568143` size of the hash to be used for map
7. `1.4` multiplying factor, factor to be used for map size calculation.

**Comment by shivamjawahar** [comment]
Thanks ratulsharker for your reply. Will check it out

Thanks and regards
S.jawahar

**Comment by shivamjawahar** [comment]
Using online complier http://onlinegdb.com/ i have run the coding using C++ language

**Comment by ratulSharker** [comment]
It seems [OnlineGDB](http://onlinegdb.com/) does not support cloning **Github** repositories in it. You have to manually create all the files, which are already exists in the repository. Easier way to starts with is to grab a machine with linux os running on it. Clone the repository on you machine and follow the [Readme.md](https://github.com/ratulSharker/Havec/blob/master/README.md).

Please let me know if there any further issues you are facing.

**Comment by shivamjawahar** [comment]
sure

**Comment by shivamjawahar** [comment]
dataset_1_7GB.fa what it represents?

**Comment by ratulSharker** [comment]
Please consider closing this issue as you successfully run `Havec`. This question does not relevant to this project issues section.

**Comment by shivamjawahar** [comment]
thank u
